If not authorized on an audio file, show the default waveform poster
sul-dlss/sul-embed pull request #1912
Opened 2023-12-04 22:00 UTC by aaron-collier

Closes #1761 

When not authorized and the file is audio:

![Screenshot 2023-12-04 at 1 57 31 PM](https://github.com/sul-dlss/sul-embed/assets/2294288/7eec084c-1da5-48d7-ba7b-2af6e95c1feb)

Video shows the poster:

![Screenshot 2023-12-04 at 1 59 13 PM](https://github.com/sul-dlss/sul-embed/assets/2294288/028cbd15-6fb6-4508-a6a0-fb39d321add4)

2023-12-04 22:13 UTC, jcoyne requested changes
Shouldn't this support the provided poster image if one is provided when logged out? For example, I think https://sul-purl-stage.stanford.edu/hj997tt0155 should display the tape.

2023-12-04 22:27 UTC, aaron-collier commented
@jcoyne suggestion on how to select that image as the poster? The `poster` attribute on the audio player is the waveform image:

```
<audio id="sul-embed-media-0" data-auth-url="https://sul-stacks-stage.stanford.edu/media/hj997tt0155/bh009rf1857_a_sl.m4a/auth_check" data-media-tag-target="mediaTag" poster="https://embed-stage.stanford.edu/assets/waveform-audio-poster-2120200a7da69d5cb6a3937536d602e0aeaa6086.svg" controls="controls" crossorigin="anonymous" class="sul-embed-media-file" height="100%"><source src="https://sul-streaming-stage.stanford.edu/stacks/_definst_/hj/997/tt/0155/mp4:bh009rf1857_a_sl.m4a/playlist.m3u8" type="application/x-mpegURL"></audio>
```

2023-12-05 04:46 UTC, jcoyne commented
@aaron-collier you're right my mistake.  We should find/create a test case that actually has a thumbnail though.

2023-12-05 20:37 UTC, andrewjbtw commented
Prod example with a dedicated poster for the item: https://purl.stanford.edu/jz314xw3742

2023-12-05 20:38 UTC, andrewjbtw commented
I can make that into a stage example with restricted rights.

2023-12-05 21:51 UTC, andrewjbtw commented
I posted on Slack too, but here's an audio poster with Stanford restrictions in stage: https://sul-purl-stage.stanford.edu/tw581qt4975

2023-12-06 16:32 UTC, aaron-collier commented on app/components/embed/media_with_companion_windows_component.html.erb
> +      <div data-controller="locked-audio-poster" data-action="auth-success@window->locked-audio-poster#hide auth-denied@window->locked-audio-poster#show" tabindex="-1" role="presentation" style="disp
Sure. Using the display style is what is done for the media poster, so I was following that pattern. Is that something that should be updated on both?

2023-12-06 16:34 UTC, aaron-collier commented
@jcoyne regarding behavior: the `filter` here would select whichever one has a iiif `default.jpg` (this is probably a bit fragile so there may be a better way to determine if an object isn't using the default poster).

2023-12-06 16:50 UTC, jcoyne commented
@aaron-collier do we need to care?  Can't we just grab the poster attribute and put it in the image tag?

2023-12-06 16:55 UTC, aaron-collier commented
Ah, are you suggesting to just use the poster value whether it's default or not? Yeah, I can certainly do that.

2023-12-06 18:13 UTC, jcoyne requested changes

2023-12-07 22:39 UTC, jcoyne approved these changes

2023-12-07 22:39 UTC, merged